/** Honest M1 copy. No synthetic names, prices, waits, ratings, or face-recognition claims. */

export const COPY = {
  ar: {
    skip: 'تخطّ إلى المحتوى',
    product: 'راكان',
    intro: 'راكان مساعد رقمي من ذا ويكند، وليس حلاقاً بشرياً.',
    landing_eyebrow: 'مراجعة المالك — راكان',
    landing_title: 'محادثة، موجز موافَق، صندوق الفريق، وتفضيلات نصية.',
    landing_body: 'لا تعرّف بالوجه، ولا دليل ضيوف عبر الفروع، ولا حفظ يتم في المتصفح وحده. ما يظهر هو ما يرسله الخادم.',
    checking: 'جاري التحقق من الحالة',
    conversation: 'المحادثة',
    brief: 'الموجز',
    preferences: 'التفضيلات',
    inbox: 'صندوق الفريق',
    capability: 'الحالة',
    composer_label: 'رسالتك لراكان',
    composer_placeholder: 'اكتب نصاً — الصورة اختيارية',
    send: 'إرسال',
    continue_without_photo: 'نكمل بدون صورة',
    photo_optional: 'الصورة اختيارية. الحجز والنص يعملان بدونها.',
    photo_unavailable: 'تحليل الصورة غير متاح في هذه الجلسة.',
    photo_preview_blocked: 'لا معاينة للصورة قبل أن تكون القدرة مفعّلة وإيصال photo_analysis سارياً.',
    image_ref: 'مرجع صورة من الخادم',
    not_inferred: 'لا يُستدل على',
    limitations: 'حدود الرصد',
    feasible_true: 'قد تكون ممكنة حضورياً — ليست ضماناً',
    feasible_unknown: 'الإمكانية غير مؤكدة حتى يراجعها الحلاق',
    proposed_inert: 'اقتراحات النموذج — غير قابلة للتنفيذ حتى يحوّلها الخادم إلى إجراء مسموح',
    actions: 'إجراءات الخادم',
    no_actions: 'لا إجراءات مسموحة من الخادم حالياً.',
    loading: 'جاري التحميل',
    empty_messages: 'ابدأ بنص. لا حاجة لصورة.',
    empty_inbox: 'لا موجزات لهذا الفرع.',
    empty_prefs: 'لا تفضيلات نصية محفوظة.',
    empty_brief: 'لا موجز موافَق من الخادم.',
    retry: 'إعادة المحاولة',
    timeout_keep: 'النص ما زال في المسودة. لم نُكمل الطلب.',
    unavailable: 'هذه القدرة غير متاحة.',
    validation: 'تحقق من الحقل',
    failed_save: 'لم يُحفظ. الحالة السابقة باقية.',
    pending: 'قيد الانتظار — ليست نتيجة ناجحة',
    saved: 'تم بعد نتيجة الخادم',
    handoff: 'تسليم خارجي لصفحة الحجز الرسمية — ليس تأكيداً لموعد',
    booking_unconfirmed: 'الحجز الرسمي تسليم خارجي، وليس موعداً مؤكداً.',
    share_text: 'مشاركة نص الموجز',
    share_photo: 'مشاركة مرجع الصورة',
    share_separate: 'مشاركة النص ومشاركة الصورة إجراءان منفصلان.',
    barber_pref: 'تفضيل الحلاق — ليس تخصيص كرسي أو موعد',
    branch_pref: 'تفضيل الفرع — فرع واحد في هذه المرحلة',
    provenance: 'الأصل',
    approved_at: 'موافقة صاحب العلاقة',
    draft_brief: 'مسودة — ليست موجزاً موافَقاً',
    preference_proposal: 'اقتراح',
    preference_approved: 'تفضيل موافَق',
    preference_executed_hidden: 'نتيجة منفَّذة ليست حقيقة M1 — لن تُعرض كقصة منفَّذة',
    version: 'الإصدار',
    version_conflict: 'تعارض إصدار. أعد التحميل من الخادم.',
    save_pref: 'حفظ التفضيل',
    delete_pref: 'حذف التفضيل',
    ack: 'تأكيد الاطلاع',
    ack_not_booking: 'الاطلاع ليس حجزاً.',
    no_success_before_receipt: 'لا نجاح قبل إيصال التسليم.',
    reconnect: 'أعيد الاتصال. إجراءات الجلسة السابقة لم تعد صالحة تلقائياً.',
    m2_unavailable: 'هذه الشاشة غير متاحة في M1.',
    session: 'جلسة',
    role: 'الدور',
    passcode: 'رمز الدخول',
    enter: 'دخول',
    customer_shell: 'واجهة الضيف',
    staff_shell: 'واجهة الفريق',
    model: 'النموذج',
    photo: 'الصورة',
    booking: 'الحجز',
    staff_inbox: 'صندوق الفريق',
    prefs_cap: 'التفضيلات',
    store: 'التخزين',
    cap_real: 'حقيقي',
    cap_mock: 'تجريبي محلي فقط',
    cap_unavailable: 'غير متاح',
    cap_enabled: 'مفعّل',
    cap_disabled: 'موقوف',
    cap_official: 'رابط رسمي (تسليم خارجي)',
    cap_pending_req: 'طلب غير مؤكد لمشغّل يراقب الصندوق',
    cap_ok: 'سليم',
    cap_degraded: 'متدهور',
    do_not: 'تجنّب',
    requested_look: 'الشكل المطلوب',
    reference_none: 'بدون مرجع صورة',
    reference_photo: 'مرجع صورة (إيصال مشاركة منفصل)',
    subject: 'المعرّف',
    flags: 'علامات المحادثة',
    gallery: 'معرض الحالات من العقود',
    live: 'جلسة حية',
  },
  en: {
    skip: 'Skip to content',
    product: 'Rakan',
    intro: 'Rakan is The Weekend’s digital assistant, not a human barber.',
    landing_eyebrow: 'Owner review — Rakan',
    landing_title: 'Conversation, approved brief, staff inbox, and text preferences.',
    landing_body: 'No face recognition, no cross-branch guest directory, no browser-only save. The UI shows what the server sends.',
    checking: 'Checking status',
    conversation: 'Conversation',
    brief: 'Brief',
    preferences: 'Preferences',
    inbox: 'Staff inbox',
    capability: 'Status',
    composer_label: 'Message to Rakan',
    composer_placeholder: 'Write text — a photo is optional',
    send: 'Send',
    continue_without_photo: 'Continue without a photo',
    photo_optional: 'A photo is optional. Booking and text work without one.',
    photo_unavailable: 'Photo analysis is not available in this session.',
    photo_preview_blocked: 'No image preview until photo is enabled and a photo_analysis receipt is active.',
    image_ref: 'Server image reference',
    not_inferred: 'Not inferred',
    limitations: 'Observation limits',
    feasible_true: 'May be feasible in person — not a guarantee',
    feasible_unknown: 'Feasibility unknown until the barber reviews it',
    proposed_inert: 'Model proposals — not executable until the server issues an AllowedAction',
    actions: 'Server actions',
    no_actions: 'No server-allowed actions right now.',
    loading: 'Loading',
    empty_messages: 'Start with text. No photo required.',
    empty_inbox: 'No briefs for this branch.',
    empty_prefs: 'No saved text preferences.',
    empty_brief: 'No approved brief from the server.',
    retry: 'Retry',
    timeout_keep: 'Draft text is kept. The request did not finish.',
    unavailable: 'This capability is unavailable.',
    validation: 'Check this field',
    failed_save: 'Not saved. The previous state remains.',
    pending: 'Pending — not a success',
    saved: 'Recorded after the server result',
    handoff: 'External handoff to the official booking page — not a confirmed appointment',
    booking_unconfirmed: 'Official booking is an external handoff, not a confirmed slot.',
    share_text: 'Share brief text',
    share_photo: 'Share photo reference',
    share_separate: 'Text share and photo share are separate actions.',
    barber_pref: 'Barber preference — not a chair or slot allocation',
    branch_pref: 'Branch preference — one branch in this milestone',
    provenance: 'Provenance',
    approved_at: 'Subject approval',
    draft_brief: 'Draft — not an approved brief',
    preference_proposal: 'Proposal',
    preference_approved: 'Approved preference',
    preference_executed_hidden: 'An executed result is not M1 truth and is not shown as a completed cut',
    version: 'Version',
    version_conflict: 'Version conflict. Reload from the server.',
    save_pref: 'Save preference',
    delete_pref: 'Delete preference',
    ack: 'Acknowledge',
    ack_not_booking: 'Acknowledgement is not a booking.',
    no_success_before_receipt: 'No success before a delivery receipt.',
    reconnect: 'Reconnected. Previous action ids are not reused silently.',
    m2_unavailable: 'This screen is unavailable in M1.',
    session: 'Session',
    role: 'Role',
    passcode: 'Passcode',
    enter: 'Enter',
    customer_shell: 'Customer',
    staff_shell: 'Staff',
    model: 'Model',
    photo: 'Photo',
    booking: 'Booking',
    staff_inbox: 'Staff inbox',
    prefs_cap: 'Preferences',
    store: 'Store',
    cap_real: 'real',
    cap_mock: 'mock (local only)',
    cap_unavailable: 'unavailable',
    cap_enabled: 'enabled',
    cap_disabled: 'disabled',
    cap_official: 'official link (external handoff)',
    cap_pending_req: 'pending request (unconfirmed)',
    cap_ok: 'ok',
    cap_degraded: 'degraded',
    do_not: 'Do not',
    requested_look: 'Requested look',
    reference_none: 'No photo reference',
    reference_photo: 'Photo reference (separate sharing receipt)',
    subject: 'Subject',
    flags: 'Conversation flags',
    gallery: 'Contract state gallery',
    live: 'Live session',
  },
};

const MESSAGE_KEYS = {
  'booking.external_handoff': { ar: COPY.ar.handoff, en: COPY.en.handoff },
  'action.stale': { ar: COPY.ar.failed_save, en: COPY.en.failed_save },
  'action.expired': { ar: COPY.ar.failed_save, en: COPY.en.failed_save },
  'action.done': { ar: COPY.ar.saved, en: COPY.en.saved },
  'action.save_preference': { ar: COPY.ar.saved, en: COPY.en.saved },
  'action.delete_preference': { ar: COPY.ar.saved, en: COPY.en.saved },
  'action.continue_without_photo': { ar: COPY.ar.continue_without_photo, en: COPY.en.continue_without_photo },
  'brief.shared_text': { ar: COPY.ar.share_text, en: COPY.en.share_text },
  'brief.shared_photo': { ar: COPY.ar.share_photo, en: COPY.en.share_photo },
  'booking.pending_unconfirmed': { ar: COPY.ar.pending, en: COPY.en.pending },
  'handoff.queued': { ar: COPY.ar.pending, en: COPY.en.pending },
  'preference.version_conflict': { ar: COPY.ar.version_conflict, en: COPY.en.version_conflict },
  'model.unavailable': { ar: 'النموذج غير مُعد.', en: 'The model is not configured.' },
  'model.timeout': { ar: COPY.ar.timeout_keep, en: COPY.en.timeout_keep },
  'model.budget_exceeded': { ar: 'توقفنا عند حد الاستخدام.', en: 'The usage cap was reached.' },
  'model.session_cap': { ar: 'وصلت هذه الجلسة حدّها من الرسائل.', en: 'This session reached its message limit.' },
  'model.temporarily_unavailable': { ar: 'راكان مو متاح هاللحظة. جرّب بعد شوي.', en: 'Rakan is not available right now. Try again shortly.' },
  'model.misconfigured': { ar: 'إعداد النموذج غير صحيح. أبلغ الفريق.', en: 'The model is misconfigured. Tell the team.' },
  'agent.ungrounded_price': { ar: 'ما أقدر أأكد السعر من هنا؛ الأسعار كاملة في صفحة الحجز.', en: 'The price could not be confirmed here; full prices are on the booking page.' },
  'agent.ungrounded_fact': { ar: 'ما أقدر أأكد التفاصيل من هنا؛ التفاصيل كاملة في صفحة الحجز.', en: 'The details could not be confirmed here; full details are on the booking page.' },
  'agent.ungrounded_link': { ar: 'ما فيه رابط مؤكد لهذا؛ صفحة الحجز الرسمية متاحة.', en: 'No confirmed link for this; the official booking page is available.' },
  'agent.invalid_output': { ar: 'صار خلل بسيط. أعد رسالتك.', en: 'A small glitch happened. Send your message again.' },
  'agent.contract_invalid': { ar: 'صار خلل بسيط. أعد رسالتك.', en: 'A small glitch happened. Send your message again.' },
  'agent.refused': { ar: 'ما أقدر أساعد بهذا الطلب.', en: 'This request cannot be helped with.' },
  'photo.consent_required': { ar: 'الصورة تحتاج موافقة صريحة. يمكن المتابعة بالنص.', en: 'A photo needs explicit consent. You can continue with text.' },
  'store.unavailable': { ar: 'التخزين غير متاح.', en: 'The store is unavailable.' },
  'upload.rejected': { ar: 'رُفض الرفع. المسار النصي ما زال متاحاً.', en: 'Upload rejected. The text path remains.' },
  'input.invalid': { ar: COPY.ar.validation, en: COPY.en.validation },
  'session.invalid': { ar: 'الجلسة غير صالحة.', en: 'The session is not valid.' },
};

export function t(locale, key) {
  const pack = locale === 'en' ? COPY.en : COPY.ar;
  return pack[key] ?? COPY.ar[key] ?? key;
}

export function messageFromKey(messageKey, locale = 'ar') {
  if (typeof messageKey !== 'string' || !messageKey) return '';
  const hit = MESSAGE_KEYS[messageKey];
  if (!hit) return messageKey;
  return locale === 'en' ? hit.en : hit.ar;
}

export function capabilityLabel(name, value, locale = 'ar') {
  const labels = {
    real: t(locale, 'cap_real'),
    mock: t(locale, 'cap_mock'),
    unavailable: t(locale, 'cap_unavailable'),
    enabled: t(locale, 'cap_enabled'),
    disabled: t(locale, 'cap_disabled'),
    official_link: t(locale, 'cap_official'),
    pending_request: t(locale, 'cap_pending_req'),
    ok: t(locale, 'cap_ok'),
    degraded: t(locale, 'cap_degraded'),
  };
  const title = t(locale, name === 'preferences' ? 'prefs_cap' : name === 'staff_inbox' ? 'staff_inbox' : name);
  return `${title}: ${labels[value] ?? value}`;
}

export function notInferredLabel(token, locale = 'ar') {
  const ar = {
    identity: 'الهوية',
    age: 'العمر',
    ethnicity: 'الأصل',
    health: 'الحالة الصحية',
    attractiveness: 'الجاذبية',
    gender: 'الجندر',
  };
  const en = {
    identity: 'identity',
    age: 'age',
    ethnicity: 'ethnicity',
    health: 'health',
    attractiveness: 'attractiveness',
    gender: 'gender',
  };
  return locale === 'en' ? (en[token] ?? token) : (ar[token] ?? token);
}
