/** Honest M1 copy. No synthetic names, prices, waits, ratings, or face-recognition claims. */

export const COPY = {
  ar: {
    skip: 'تخطّ إلى المحتوى',
    product: 'راكان',
    intro: 'راكان مساعد رقمي من ذا ويكند، وليس حلاقاً بشرياً.',
    landing_eyebrow: 'مراجعة المالك — راكان',
    landing_title: 'محادثة، موجز موافَق، صندوق الفريق، وتفضيلات نصية.',
    landing_body: 'لا تعرّف بالوجه، ولا دليل ضيوف عبر الفروع، ولا حفظ يتم في المتصفح وحده. ما يظهر هو ما يرسله الخادم.',
    checking: 'جاري التحقق من الحالة',
    conversation: 'المحادثة',
    brief: 'الموجز',
    preferences: 'التفضيلات',
    inbox: 'صندوق الفريق',
    capability: 'الحالة',
    composer_label: 'رسالتك لراكان',
    composer_placeholder: 'اكتب نصاً — الصورة اختيارية',
    send: 'إرسال',
    continue_without_photo: 'نكمل بدون صورة',
    photo_optional: 'الصورة اختيارية. الحجز والنص يعملان بدونها.',
    photo_unavailable: 'تحليل الصورة غير متاح في هذه الجلسة.',
    photo_preview_blocked: 'لا معاينة للصورة قبل أن تكون القدرة مفعّلة وإيصال photo_analysis سارياً.',
    image_ref: 'مرجع صورة من الخادم',
    not_inferred: 'لا يُستدل على',
    limitations: 'حدود الرصد',
    feasible_true: 'قد تكون ممكنة حضورياً — ليست ضماناً',
    feasible_unknown: 'الإمكانية غير مؤكدة حتى يراجعها الحلاق',
    proposed_inert: 'اقتراحات النموذج — غير قابلة للتنفيذ حتى يحوّلها الخادم إلى إجراء مسموح',
    actions: 'إجراءات الخادم',
    no_actions: 'لا إجراءات مسموحة من الخادم حالياً.',
    loading: 'جاري التحميل',
    empty_messages: 'ابدأ بنص. لا حاجة لصورة.',
    empty_inbox: 'لا موجزات لهذا الفرع.',
    empty_prefs: 'لا تفضيلات نصية محفوظة.',
    empty_brief: 'لا موجز موافَق من الخادم.',
    retry: 'إعادة المحاولة',
    timeout_keep: 'النص ما زال في المسودة. لم نُكمل الطلب.',
    unavailable: 'هذه القدرة غير متاحة.',
    validation: 'تحقق من الحقل',
    failed_save: 'لم يُحفظ. الحالة السابقة باقية.',
    pending: 'قيد الانتظار — ليست نتيجة ناجحة',
    saved: 'تم بعد نتيجة الخادم',
    handoff: 'تسليم خارجي لصفحة الحجز الرسمية — ليس تأكيداً لموعد',
    booking_unconfirmed: 'الحجز الرسمي تسليم خارجي، وليس موعداً مؤكداً.',
    share_text: 'مشاركة نص الموجز',
    share_photo: 'مشاركة ملاحظات الصورة',
    share_separate: 'مشاركة النص ومشاركة ملاحظات الصورة إجراءان منفصلان. المشاركة ترسل ملاحظات مكتوبة وليست صورة.',
    value_text: 'نص التفضيل',
    booking_handoff: 'الحجز',
    photo_analysis: 'تحليل الصورة',
    text_preferences: 'التفضيلات النصية',
    staff_sharing_text: 'مشاركة نص الموجز',
    staff_sharing_photo: 'مشاركة ملاحظات الصورة',
    pref_kind_style: 'القصة',
    pref_kind_barber: 'الحلاق',
    pref_kind_branch: 'الفرع',
    pref_kind_do_not: 'تجنّب',
    pref_kind_note: 'ملاحظة',
    consent_grant: 'أوافق',
    consent_revoke: 'سحب الموافقة',
    consent_later: 'لاحقاً',
    consent_optional: 'هذا الإذن اختياري.',
    approve_brief: 'اعتماد الموجز',
    photo_upload: 'رفع صورة (اختياري)',
    notice_photo_analysis: 'تحليل الصورة اختياري. نستخدمها لهذه الجلسة لملاحظات تجميلية عن الشعر واللحية والمظهر الظاهر فقط. لا تعرّف بالوجه ولا تشخيص. يمكنك المتابعة بدون صورة.',
    notice_text_preferences: 'حفظ التفضيلات النصية اختياري. تُحفظ حتى تسحب الموافقة أو حتى انتهاء مدة الاحتفاظ، ويمكن حذفها.',
    notice_staff_sharing_text: 'مشاركة نص الموجز مع فريق الفرع تحتاج موافقتك. المشاركة ليست حجزاً ولا تأكيداً لموعد.',
    notice_staff_sharing_photo: 'مشاركة ملاحظات الصورة تعطي الفريق ملاحظات مكتوبة عن الصورة، وليست إرسال الصورة نفسها.',
    barber_pref: 'تفضيل الحلاق — ليس تخصيص كرسي أو موعد',
    branch_pref: 'تفضيل الفرع — فرع واحد في هذه المرحلة',
    provenance: 'الأصل',
    approved_at: 'موافقة صاحب العلاقة',
    draft_brief: 'مسودة — ليست موجزاً موافَقاً',
    preference_proposal: 'اقتراح',
    preference_approved: 'تفضيل موافَق',
    preference_executed_hidden: 'نتيجة منفَّذة ليست حقيقة M1 — لن تُعرض كقصة منفَّذة',
    version: 'الإصدار',
    version_conflict: 'تعارض إصدار. أعد التحميل من الخادم.',
    save_pref: 'حفظ التفضيل',
    delete_pref: 'حذف التفضيل',
    ack: 'تأكيد الاطلاع',
    ack_not_booking: 'الاطلاع ليس حجزاً.',
    no_success_before_receipt: 'لا نجاح قبل إيصال التسليم.',
    reconnect: 'أعيد الاتصال. إجراءات الجلسة السابقة لم تعد صالحة تلقائياً.',
    m2_unavailable: 'هذه الشاشة غير متاحة في M1.',
    session: 'جلسة',
    role: 'الدور',
    passcode: 'رمز الدخول',
    enter: 'دخول',
    customer_shell: 'واجهة الضيف',
    staff_shell: 'واجهة الفريق',
    model: 'النموذج',
    photo: 'الصورة',
    booking: 'الحجز',
    staff_inbox: 'صندوق الفريق',
    prefs_cap: 'التفضيلات',
    store: 'التخزين',
    cap_real: 'حقيقي',
    cap_mock: 'تجريبي محلي فقط',
    cap_unavailable: 'غير متاح',
    cap_enabled: 'مفعّل',
    cap_disabled: 'موقوف',
    cap_official: 'رابط رسمي (تسليم خارجي)',
    cap_pending_req: 'طلب غير مؤكد لمشغّل يراقب الصندوق',
    cap_ok: 'سليم',
    cap_degraded: 'متدهور',
    do_not: 'تجنّب',
    requested_look: 'الشكل المطلوب',
    reference_none: 'بدون مرجع صورة',
    reference_photo: 'مرجع صورة (إيصال مشاركة منفصل)',
    subject: 'المعرّف',
    flags: 'علامات المحادثة',
    gallery: 'معرض الحالات من العقود',
    live: 'جلسة حية',
    handoff_queue: 'طلبات التحدث مع الفريق',
    handoff_queue_empty: 'ما فيه طلب تحدث مع الفريق حالياً.',
    handoff_received: 'وصل الطلب. ما انقبل بعد.',
    handoff_accepted: 'قبلت الطلب. الرد الآلي متوقف لهذه الجلسة.',
    handoff_accepted_by_other: 'قبل الطلب موظف آخر.',
    handoff_accept: 'قبول الطلب',
    handoff_release: 'إفلات الطلب',
    handoff_not_accepted_until_click: 'ما نقول إن الفريق استلم إلا بعد زر القبول.',
    photo_notes: 'ملاحظات الصورة (نص)',
    photo_notes_not_image: 'هذي ملاحظات مكتوبة عن الصورة، مو الصورة نفسها.',
    obs_hair_length: 'طول الشعر الظاهر',
    obs_hair_texture: 'ملمس الشعر الظاهر',
    obs_beard: 'شكل اللحية الظاهر',
    obs_top_density_visible: 'كثافة الظاهر من فوق',
    obs_face_visible: 'وضوح الوجه',
    obs_confidence: 'الثقة',
  },
  en: {
    skip: 'Skip to content',
    product: 'Rakan',
    intro: 'Rakan is The Weekend’s digital assistant, not a human barber.',
    landing_eyebrow: 'Owner review — Rakan',
    landing_title: 'Conversation, approved brief, staff inbox, and text preferences.',
    landing_body: 'No face recognition, no cross-branch guest directory, no browser-only save. The UI shows what the server sends.',
    checking: 'Checking status',
    conversation: 'Conversation',
    brief: 'Brief',
    preferences: 'Preferences',
    inbox: 'Staff inbox',
    capability: 'Status',
    composer_label: 'Message to Rakan',
    composer_placeholder: 'Write text — a photo is optional',
    send: 'Send',
    continue_without_photo: 'Continue without a photo',
    photo_optional: 'A photo is optional. Booking and text work without one.',
    photo_unavailable: 'Photo analysis is not available in this session.',
    photo_preview_blocked: 'No image preview until photo is enabled and a photo_analysis receipt is active.',
    image_ref: 'Server image reference',
    not_inferred: 'Not inferred',
    limitations: 'Observation limits',
    feasible_true: 'May be feasible in person — not a guarantee',
    feasible_unknown: 'Feasibility unknown until the barber reviews it',
    proposed_inert: 'Model proposals — not executable until the server issues an AllowedAction',
    actions: 'Server actions',
    no_actions: 'No server-allowed actions right now.',
    loading: 'Loading',
    empty_messages: 'Start with text. No photo required.',
    empty_inbox: 'No briefs for this branch.',
    empty_prefs: 'No saved text preferences.',
    empty_brief: 'No approved brief from the server.',
    retry: 'Retry',
    timeout_keep: 'Draft text is kept. The request did not finish.',
    unavailable: 'This capability is unavailable.',
    validation: 'Check this field',
    failed_save: 'Not saved. The previous state remains.',
    pending: 'Pending — not a success',
    saved: 'Recorded after the server result',
    handoff: 'External handoff to the official booking page — not a confirmed appointment',
    booking_unconfirmed: 'Official booking is an external handoff, not a confirmed slot.',
    share_text: 'Share brief text',
    share_photo: 'Share photo notes',
    share_separate: 'Text share and photo-note share are separate actions. Sharing sends written observations, never an image.',
    value_text: 'Preference text',
    booking_handoff: 'Booking',
    photo_analysis: 'Photo analysis',
    text_preferences: 'Text preferences',
    staff_sharing_text: 'Share brief text',
    staff_sharing_photo: 'Share photo notes',
    pref_kind_style: 'Style',
    pref_kind_barber: 'Barber',
    pref_kind_branch: 'Branch',
    pref_kind_do_not: 'Do not',
    pref_kind_note: 'Note',
    consent_grant: 'I agree',
    consent_revoke: 'Withdraw consent',
    consent_later: 'Later',
    consent_optional: 'This permission is optional.',
    approve_brief: 'Approve the brief',
    photo_upload: 'Upload a photo (optional)',
    notice_photo_analysis: 'Photo analysis is optional. We use it in this session for cosmetic notes about hair, beard and visible appearance only. No face recognition and no diagnosis. You can continue without a photo.',
    notice_text_preferences: 'Saving text preferences is optional. They are kept until you withdraw consent or the retention period ends, and you can delete them.',
    notice_staff_sharing_text: 'Sharing the brief text with branch staff needs your consent. Sharing is not a booking or a confirmed appointment.',
    notice_staff_sharing_photo: 'Sharing photo notes gives staff written observations of the photo, not the image itself.',
    barber_pref: 'Barber preference — not a chair or slot allocation',
    branch_pref: 'Branch preference — one branch in this milestone',
    provenance: 'Provenance',
    approved_at: 'Subject approval',
    draft_brief: 'Draft — not an approved brief',
    preference_proposal: 'Proposal',
    preference_approved: 'Approved preference',
    preference_executed_hidden: 'An executed result is not M1 truth and is not shown as a completed cut',
    version: 'Version',
    version_conflict: 'Version conflict. Reload from the server.',
    save_pref: 'Save preference',
    delete_pref: 'Delete preference',
    ack: 'Acknowledge',
    ack_not_booking: 'Acknowledgement is not a booking.',
    no_success_before_receipt: 'No success before a delivery receipt.',
    reconnect: 'Reconnected. Previous action ids are not reused silently.',
    m2_unavailable: 'This screen is unavailable in M1.',
    session: 'Session',
    role: 'Role',
    passcode: 'Passcode',
    enter: 'Enter',
    customer_shell: 'Customer',
    staff_shell: 'Staff',
    model: 'Model',
    photo: 'Photo',
    booking: 'Booking',
    staff_inbox: 'Staff inbox',
    prefs_cap: 'Preferences',
    store: 'Store',
    cap_real: 'real',
    cap_mock: 'mock (local only)',
    cap_unavailable: 'unavailable',
    cap_enabled: 'enabled',
    cap_disabled: 'disabled',
    cap_official: 'official link (external handoff)',
    cap_pending_req: 'pending request (unconfirmed)',
    cap_ok: 'ok',
    cap_degraded: 'degraded',
    do_not: 'Do not',
    requested_look: 'Requested look',
    reference_none: 'No photo reference',
    reference_photo: 'Photo reference (separate sharing receipt)',
    subject: 'Subject',
    flags: 'Conversation flags',
    gallery: 'Contract state gallery',
    live: 'Live session',
    handoff_queue: 'Talk-to-staff requests',
    handoff_queue_empty: 'No talk-to-staff requests right now.',
    handoff_received: 'Request arrived. Not accepted yet.',
    handoff_accepted: 'You accepted this request. Autonomous replies are paused for that session.',
    handoff_accepted_by_other: 'Accepted by another staff member',
    handoff_accept: 'Accept request',
    handoff_release: 'Release request',
    handoff_not_accepted_until_click: 'Do not treat this as staff-accepted until Accept is pressed.',
    photo_notes: 'Photo notes (text)',
    photo_notes_not_image: 'These are written notes about the photo, not the image itself.',
    obs_hair_length: 'Visible hair length',
    obs_hair_texture: 'Visible hair texture',
    obs_beard: 'Visible beard',
    obs_top_density_visible: 'Visible top density',
    obs_face_visible: 'Face visibility',
    obs_confidence: 'Confidence',
  },
};

const MESSAGE_KEYS = {
  'booking.external_handoff': { ar: COPY.ar.handoff, en: COPY.en.handoff },
  'action.stale': { ar: COPY.ar.failed_save, en: COPY.en.failed_save },
  'action.expired': { ar: COPY.ar.failed_save, en: COPY.en.failed_save },
  'action.done': { ar: COPY.ar.saved, en: COPY.en.saved },
  'action.save_preference': { ar: COPY.ar.saved, en: COPY.en.saved },
  'action.delete_preference': { ar: COPY.ar.saved, en: COPY.en.saved },
  'action.continue_without_photo': { ar: COPY.ar.continue_without_photo, en: COPY.en.continue_without_photo },
  'brief.shared_text': { ar: COPY.ar.share_text, en: COPY.en.share_text },
  'brief.shared_photo': { ar: COPY.ar.share_photo, en: COPY.en.share_photo },
  'booking.pending_unconfirmed': { ar: COPY.ar.pending, en: COPY.en.pending },
  'handoff.queued': {
    ar: 'طلب التحدث مع الفريق في الانتظار. ما استلمه أحد من الفريق بعد.',
    en: 'Talk-to-staff is queued. Nobody on the team has accepted it yet.',
  },
  'handoff.accepted': {
    ar: 'طلب التحدث مع الفريق مقبول من موظف.',
    en: 'A staff member accepted the talk-to-staff request.',
  },
  'handoff.not_found': {
    ar: 'ما لقيت طلب التحدث مع الفريق.',
    en: 'That talk-to-staff request was not found.',
  },
  'preference.version_conflict': { ar: COPY.ar.version_conflict, en: COPY.en.version_conflict },
  'model.unavailable': { ar: 'النموذج غير مُعد.', en: 'The model is not configured.' },
  'model.timeout': { ar: COPY.ar.timeout_keep, en: COPY.en.timeout_keep },
  'model.budget_exceeded': { ar: 'توقفنا عند حد الاستخدام.', en: 'The usage cap was reached.' },
  'model.session_cap': { ar: 'وصلت هذه الجلسة حدّها من الرسائل.', en: 'This session reached its message limit.' },
  'model.temporarily_unavailable': { ar: 'راكان مو متاح هاللحظة. جرّب بعد شوي.', en: 'Rakan is not available right now. Try again shortly.' },
  'model.misconfigured': { ar: 'إعداد النموذج غير صحيح. أبلغ الفريق.', en: 'The model is misconfigured. Tell the team.' },
  'agent.ungrounded_price': { ar: 'ما أقدر أأكد السعر من هنا؛ الأسعار كاملة في صفحة الحجز.', en: 'The price could not be confirmed here; full prices are on the booking page.' },
  'agent.ungrounded_fact': { ar: 'ما أقدر أأكد التفاصيل من هنا؛ التفاصيل كاملة في صفحة الحجز.', en: 'The details could not be confirmed here; full details are on the booking page.' },
  'agent.ungrounded_link': { ar: 'ما فيه رابط مؤكد لهذا؛ صفحة الحجز الرسمية متاحة.', en: 'No confirmed link for this; the official booking page is available.' },
  'agent.invalid_output': { ar: 'صار خلل بسيط. أعد رسالتك.', en: 'A small glitch happened. Send your message again.' },
  'agent.contract_invalid': { ar: 'صار خلل بسيط. أعد رسالتك.', en: 'A small glitch happened. Send your message again.' },
  'agent.refused': { ar: 'ما أقدر أساعد بهذا الطلب.', en: 'This request cannot be helped with.' },
  'photo.consent_required': { ar: 'الصورة تحتاج موافقة صريحة. يمكن المتابعة بالنص.', en: 'A photo needs explicit consent. You can continue with text.' },
  'preference.consent_required': { ar: COPY.ar.notice_text_preferences, en: COPY.en.notice_text_preferences },
  'action.consent_required': { ar: 'هذا الإجراء يحتاج موافقة صريحة أولاً.', en: 'This action needs explicit consent first.' },
  'brief.share_consent': { ar: COPY.ar.notice_staff_sharing_text, en: COPY.en.notice_staff_sharing_text },
  'brief.photo_consent': { ar: COPY.ar.notice_staff_sharing_photo, en: COPY.en.notice_staff_sharing_photo },
  'store.unavailable': { ar: 'التخزين غير متاح.', en: 'The store is unavailable.' },
  'upload.rejected': { ar: 'رُفض الرفع. المسار النصي ما زال متاحاً.', en: 'Upload rejected. The text path remains.' },
  'input.invalid': { ar: COPY.ar.validation, en: COPY.en.validation },
  'session.invalid': { ar: 'الجلسة غير صالحة.', en: 'The session is not valid.' },
  'session.expired': { ar: 'انتهت الجلسة. ادخل من جديد.', en: 'The session expired. Sign in again.' },
  'session.passcode': { ar: 'رمز الدخول غير صحيح.', en: 'The passcode is not correct.' },
  'session.role': { ar: 'الدور غير صالح.', en: 'The role is not valid.' },
  'session.throttled': { ar: 'محاولات كثيرة. جرّب بعد شوي.', en: 'Too many attempts. Try again shortly.' },
  'turn.invalid': { ar: 'اكتب نصاً قبل الإرسال.', en: 'Write some text before sending.' },
  'turn.session': { ar: 'الجلسة لا تطابق هذه الرسالة.', en: 'The session does not match this message.' },
  'turn.in_progress': { ar: 'الرسالة السابقة ما زالت تشتغل.', en: 'The previous message is still in progress.' },
  'preference.not_found': { ar: 'ما لقيت هذا التفضيل.', en: 'That preference was not found.' },
  'action.not_found': { ar: 'ما لقيت هذا الإجراء.', en: 'That action was not found.' },
  'action.decline': { ar: 'تم. ما فيه عرض إضافي.', en: 'Done. No further offer.' },
  'action.kind': { ar: 'نوع الإجراء غير معروف.', en: 'That action kind is not known.' },
  'http.internal': { ar: 'صار خلل في الخادم. جرّب بعد شوي.', en: 'The server hit an internal error. Try again shortly.' },
  'http.not_found': { ar: 'ما لقيت الصفحة.', en: 'That page was not found.' },
  'http.body_too_large': { ar: 'الطلب أكبر من المسموح.', en: 'The request is larger than allowed.' },
  'http.invalid_json': { ar: 'الطلب غير صالح.', en: 'The request body is not valid JSON.' },
  'http.port': { ar: 'المنفذ غير صالح.', en: 'The port is not valid.' },
  'staff.required': { ar: 'هذا المسار للفريق فقط.', en: 'This path is for staff only.' },
  'brief.role': { ar: 'الدور ما يسمح بهذا الموجز.', en: 'This role cannot use that brief.' },
  'brief.not_found': { ar: 'ما لقيت الموجز.', en: 'That brief was not found.' },
  'consent.kind': { ar: 'نوع الموافقة غير معروف.', en: 'That consent kind is not known.' },
  'consent.via': { ar: 'طريقة منح الموافقة غير مسموحة.', en: 'That way of granting consent is not allowed.' },
  'consent.not_found': { ar: 'ما لقيت إيصال الموافقة.', en: 'That consent receipt was not found.' },
  'photo.disabled': { ar: 'تحليل الصورة موقف في هذه الجلسة.', en: 'Photo analysis is disabled in this session.' },
  'booking.pending_disabled': { ar: 'طلب الموعد غير المؤكد غير متاح.', en: 'Pending booking requests are not available.' },
  'upload.not_found': { ar: 'ما لقيت مرجع الصورة.', en: 'That image reference was not found.' },
};

export function t(locale, key) {
  const pack = locale === 'en' ? COPY.en : COPY.ar;
  return pack[key] ?? COPY.ar[key] ?? key;
}

export function messageFromKey(messageKey, locale = 'ar') {
  if (typeof messageKey !== 'string' || !messageKey) return '';
  const hit = MESSAGE_KEYS[messageKey];
  if (!hit) return messageKey;
  return locale === 'en' ? hit.en : hit.ar;
}

export function capabilityLabel(name, value, locale = 'ar') {
  const labels = {
    real: t(locale, 'cap_real'),
    mock: t(locale, 'cap_mock'),
    unavailable: t(locale, 'cap_unavailable'),
    enabled: t(locale, 'cap_enabled'),
    disabled: t(locale, 'cap_disabled'),
    official_link: t(locale, 'cap_official'),
    pending_request: t(locale, 'cap_pending_req'),
    ok: t(locale, 'cap_ok'),
    degraded: t(locale, 'cap_degraded'),
  };
  let titleKey = name;
  switch (name) {
    case 'preferences':
    case 'prefs_cap':
      titleKey = 'prefs_cap';
      break;
    case 'staff_inbox':
      titleKey = 'staff_inbox';
      break;
    case 'booking_handoff':
    case 'booking':
      titleKey = 'booking';
      break;
    default:
      titleKey = name;
  }
  const title = t(locale, titleKey);
  return `${title}: ${labels[value] ?? value}`;
}

export function receiptKindLabel(kind, locale = 'ar') {
  return t(locale, kind);
}

export function preferenceKindLabel(kind, locale = 'ar') {
  return t(locale, `pref_kind_${kind}`);
}

export function notInferredLabel(token, locale = 'ar') {
  const ar = {
    identity: 'الهوية',
    age: 'العمر',
    ethnicity: 'الأصل',
    health: 'الحالة الصحية',
    attractiveness: 'الجاذبية',
    gender: 'الجندر',
  };
  const en = {
    identity: 'identity',
    age: 'age',
    ethnicity: 'ethnicity',
    health: 'health',
    attractiveness: 'attractiveness',
    gender: 'gender',
  };
  return locale === 'en' ? (en[token] ?? token) : (ar[token] ?? token);
}
